# Default values for health-checker.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 0

image:
  repository: useparagon/health-checker
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: '2025.1215.1845-d85aba8f'

service:
  type: ClusterIP
  port: 1733

resources:
  limits:
    memory: 100Mi
  requests:
    cpu: 100m
    memory: 100Mi

terminationGracePeriodSeconds: 120

pdb:
  enabled: true
  maxUnavailable: 0

autoscaling:
  enabled: false
  # minReplicas: 1
  # maxReplicas: 1
  # targetCPUUtilizationPercentage: 75
  # targetMemoryUtilizationPercentage: 75

secretName: "paragon-secrets"

secretKeys:
  - CACHE_REDIS_URL
  - CERBERUS_POSTGRES_DATABASE
  - CERBERUS_POSTGRES_HOST
  - CERBERUS_POSTGRES_PASSWORD
  - CERBERUS_POSTGRES_PORT
  - CERBERUS_POSTGRES_USERNAME
  - CLOUD_STORAGE_MICROSERVICE_PASS
  - CLOUD_STORAGE_MICROSERVICE_USER
  - HERMES_POSTGRES_DATABASE
  - HERMES_POSTGRES_HOST
  - HERMES_POSTGRES_PASSWORD
  - HERMES_POSTGRES_PORT
  - HERMES_POSTGRES_USERNAME
  - PHEME_POSTGRES_DATABASE
  - PHEME_POSTGRES_HOST
  - PHEME_POSTGRES_PASSWORD
  - PHEME_POSTGRES_PORT
  - PHEME_POSTGRES_USERNAME
  - QUEUE_REDIS_URL
  - SYSTEM_REDIS_URL
  - WORKFLOW_REDIS_URL
  - ZEUS_POSTGRES_DATABASE
  - ZEUS_POSTGRES_HOST
  - ZEUS_POSTGRES_PASSWORD
  - ZEUS_POSTGRES_PORT
  - ZEUS_POSTGRES_USERNAME

envKeys:
  - ACCOUNT_PRIVATE_URL
  - CERBERUS_PRIVATE_URL
  - CLOUD_STORAGE_PUBLIC_BUCKET
  - CLOUD_STORAGE_REGION
  - CLOUD_STORAGE_SYSTEM_BUCKET
  - CLOUD_STORAGE_TYPE
  - CONNECT_PRIVATE_URL
  - DASHBOARD_PRIVATE_URL
  - HADES_PRIVATE_URL
  - HEALTH_CHECKER_PORT
  - HEALTH_CHECKER_PRIVATE_URL
  - HEALTH_CHECKER_PUBLIC_URL
  - HERMES_PRIVATE_URL
  - PASSPORT_PRIVATE_URL
  - PHEME_PRIVATE_URL
  - RELEASE_PRIVATE_URL
  - WORKER_ACTIONKIT_PRIVATE_URL
  - WORKER_ACTIONS_PRIVATE_URL
  - WORKER_CREDENTIALS_PRIVATE_URL
  - WORKER_CRONS_PRIVATE_URL
  - WORKER_DEPLOYMENTS_PRIVATE_URL
  - WORKER_PROXY_PRIVATE_URL
  - WORKER_TRIGGERS_PRIVATE_URL
  - WORKER_WORKFLOWS_PRIVATE_URL
  - ZEUS_PRIVATE_URL

imagePullSecrets:
  - name: docker-cfg
nameOverride: ''
fullnameOverride: 'health-checker'

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ''

podSecurityContext:
  {}
# fsGroup: 2000

securityContext:
  {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
# runAsUser: 1000

ingress:
  certificate: ''
  enabled: true
  className: ''
  host: '' # When empty, will use chart name + domain
  healthcheck_path: /healthz
  include_annotations: true

nodeSelector: {}

tolerations: []

affinity:
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 1
      preference:
        matchExpressions:
        - key: useparagon.com/capacityType
          operator: In
          values:
          - ondemand

tls_secret: ''
