{{- if and (eq .Values.mode "deployment") (or (not .Values.pdb) .Values.pdb.enabled) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "ocs-code-runner.fullname" . }}
  labels:
    {{- include "ocs-code-runner.labels" . | nindent 4 }}
spec:
  maxUnavailable: {{ (.Values.pdb).maxUnavailable | default 1 }}
  selector:
    matchLabels:
      {{- include "ocs-code-runner.selectorLabels" . | nindent 6 }}
{{- end }}
