{{- if and .Values.credsJson (eq (default "" .Values.credsSecretName) "") }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "openobserve.fullname" . }}-creds
  labels:
    {{- include "openobserve.labels" . | nindent 4 }}
data:
  creds.json: |
    {{- .Values.credsJson | b64dec | nindent 4 }}
{{- end }}
