---
# create statefulset
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "openobserve.fullname" . }}
  labels:
    {{- include "openobserve.labels" . | nindent 4 }}
{{- $podAnnotations := dict -}}
{{- if and .Values.global (kindIs "map" .Values.global) (hasKey .Values.global "podAnnotations") (kindIs "map" .Values.global.podAnnotations) -}}
{{- $podAnnotations = merge $podAnnotations .Values.global.podAnnotations -}}
{{- end -}}
{{- if .Values.podAnnotations -}}
{{- $podAnnotations = merge $podAnnotations .Values.podAnnotations -}}
{{- end -}}
spec:
  serviceName: {{ include "openobserve.fullname" . }}
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      {{- include "openobserve.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- if $podAnnotations }}
      annotations:
        {{- toYaml $podAnnotations | nindent 8 }}
      {{- end }}
      labels:
        {{- include "openobserve.selectorLabels" . | nindent 8 }}
    spec:
      {{- $pullSecrets := include "paragon.imagePullSecrets" (dict "root" .) -}}
      {{- if $pullSecrets }}
      imagePullSecrets:
        {{- $pullSecrets | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "openobserve.serviceAccountName" . }}
      securityContext:
        fsGroup: 2000
        runAsUser: 10000
        runAsGroup: 3000
        runAsNonRoot: true
      containers:
        - name: {{ include "openobserve.fullname" . }}
          image: {{ include "paragon.image" (dict "root" . "repository" (.Values.image.repository | default "public.ecr.aws/zinclabs/openobserve") "tag" (.Values.image.tag | default "latest")) | quote }}
          imagePullPolicy: {{ include "paragon.imagePullPolicy" (dict "root" .) }}
          env:
            {{- /* Handle environment variables */}}
            {{- if and .Values.envKeys (kindIs "slice" .Values.envKeys) }}
            {{- range $key := .Values.envKeys }}
            {{- if and $.Values.env (kindIs "map" $.Values.env) (hasKey $.Values.env $key) }}
            - name: {{ $key }}
              value: {{ index $.Values.env $key | quote }}
            {{- else if and $.Values.global.env (kindIs "map" $.Values.global.env) (hasKey $.Values.global.env $key) }}
            - name: {{ $key }}
              value: {{ index $.Values.global.env $key | quote }}
            {{- end }}
            {{- end }}
            {{- end }}
            {{- /* Handle secrets */}}
            {{- if and .Values.secretKeys (kindIs "slice" .Values.secretKeys) }}
            {{- range $key := .Values.secretKeys }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  name: {{ if and $.Values.secrets (kindIs "map" $.Values.secrets) (hasKey $.Values.secrets $key) }}{{ $.Values.secretName }}-{{ $.Chart.Name }}{{ else }}{{ $.Values.secretName }}{{ end }}
                  key: {{ $key }}
                  optional: true
            {{- end }}
            {{- end }}
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu | default "4096m" }}
              memory: {{ .Values.resources.limits.memory | default "2048Mi" }}
            requests:
              cpu: {{ .Values.resources.requests.cpu | default "256m" }}
              memory: {{ .Values.resources.requests.memory | default "50Mi" }}
          ports:
            - containerPort: {{ .Values.service.port }}
              name: http
          volumeMounts:
          - name: openobserve-data
            mountPath: /data
          {{- if or .Values.credsSecretName .Values.credsJson }}
          - name: openobserve-creds
            mountPath: /creds
          {{- end }}
      volumes:
        {{- if .Values.credsSecretName }}
        - name: openobserve-creds
          secret:
            secretName: {{ .Values.credsSecretName | quote }}
        {{- else if .Values.credsJson }}
        - name: openobserve-creds
          secret:
            secretName: {{ include "openobserve.fullname" . }}-creds
        {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: openobserve-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.persistence.size | default "5Gi" }}
        {{- if eq .Values.global.env.HOST_ENV "AWS_K8" }}
        storageClassName: gp3
        {{- end }}
