variable "workspace" {
  type = string
}

variable "organization" {
  type = string
}

variable "namespace" {
  description = "Existing Kubernetes namespace where Paragon and Hoop run."
  type        = string
  default     = "paragon"
}

variable "hoop_agent_name" {
  type    = string
  default = null
}

variable "hoop_agent_id" {
  type    = string
  default = null
}

variable "hoop_key" {
  type      = string
  sensitive = true
  default   = null
}

variable "hoop_server" {
  type    = string
  default = "hoop-grpc.ops.paragoninternal.com:8443"
}

variable "hoop_version" {
  type    = string
  default = "1.87.2"
}

variable "hoop_postgres_guardrail_rules" {
  type = list(string)
}

variable "hoop_redis_guardrail_rules" {
  type = list(string)
}

variable "hoop_grafana_connection" {
  type = bool
}

variable "customer_facing" {
  type = bool
}

variable "all_access_groups" {
  type = list(string)
}

variable "restricted_access_groups" {
  type = list(string)
}

variable "reviewers_access_groups" {
  type = list(string)
}

variable "hoop_slack_bot_token" {
  type      = string
  sensitive = true
  default   = null
}

variable "hoop_slack_app_token" {
  type      = string
  sensitive = true
  default   = null
}

variable "hoop_slack_channel_ids" {
  type = list(string)
}

variable "infra_vars" {
  description = "Sensitive connection values generated by the infra Postgres and Redis modules."
  sensitive   = true
  type = object({
    postgres = object({
      value = map(object({
        host     = string
        port     = number
        user     = string
        password = string
        database = string
        sslmode  = optional(string, "disable")
      }))
    })
    redis = object({
      value = map(object({
        host           = string
        port           = number
        db_number      = optional(number, 0)
        ssl            = optional(bool, false)
        ca_certificate = optional(string, null)
        password       = optional(string)
        user           = optional(string)
      }))
    })
  })
}

variable "eks_oidc_provider_arn" {
  type = string
}

variable "eks_oidc_issuer_url" {
  type = string
}

variable "custom_connections" {
  sensitive = true
  type = map(object({
    type                  = string
    subtype               = optional(string)
    access_mode_runbooks  = optional(string, "enabled")
    access_mode_exec      = optional(string, "enabled")
    access_mode_connect   = optional(string, "disabled")
    access_schema         = optional(string, "disabled")
    command               = optional(list(string))
    secrets               = map(string)
    tags                  = optional(map(string), {})
    guardrail_rules       = optional(list(string), [])
    reviewers             = optional(list(string), [])
    access_control_groups = optional(list(string), [])
  }))
}

variable "k8s_connections" {
  sensitive = true
  type = map(object({
    type                  = optional(string, "custom")
    subtype               = optional(string)
    access_mode_runbooks  = optional(string, "enabled")
    access_mode_exec      = optional(string, "enabled")
    access_mode_connect   = optional(string, "enabled")
    access_schema         = optional(string, "disabled")
    command               = optional(list(string), ["bash"])
    remote_url            = optional(string, "https://kubernetes.default.svc.cluster.local")
    insecure              = optional(string, "true")
    namespace             = optional(string, "paragon")
    secrets               = optional(map(string), {})
    tags                  = optional(map(string), {})
    guardrail_rules       = optional(list(string), [])
    reviewers             = optional(list(string), [])
    access_control_groups = optional(list(string), [])
  }))
}
